### ISSUE TITLE
Missing associations

### ISSUE THREAD

**Issue by Matithieuu** [LucasJOLY/TuttiFrutti#16]
Hey ! 

It misses the relation between album and playlist.

It needs a ManyToMany relationship !

Regards,
M.

**Comment by LucasJOLY** [comment]
jje m'en branle travaille sur ton projet pd

**Comment by Matithieuu** [comment]
moi y a des associations one to many

**Comment by LucasJOLY** [comment]
mais toi je m'en fout complètement
